config/routes.rb
Rails.application.routes.draw do
  devise_for :users
   resources :posts
   root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user

    validates :title, length: {minimum: 5}
    validates :body, presence: true


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts      
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  def index
  	@posts = Post.all.order('created_at  DESC')
  end

  def new
  	@post = current_user.posts.build
  end
  
  def create
    @post = current_user.posts.build(post_params)
    if @post.save
    	redirect_to @post
    else
      render 'new'
     end 	
  end


  def show
  end

  def edit
  end
  
  def update

     if @post.update(post_params)
     	redirect_to @post
     else
        render 'edit'
     end
  end

   def destroy
   	 @post.destroy
   	 redirect_to root_path
    end

  private

    def find_post
       @post = Post.find(params[:id]) 
     end



     def post_params
       params.require(:post).permit(:title, :body, :user_iD)
     end 

          


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog5</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container">
          <a class="navbar-brand"><%= link_to "MyBlog",root_path, class: "btn btn-default" %></a>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "New Post", new_post_path, class: "btn btn-default" %></li>
          <li><%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "btn btn-default" %></li>
        </ul> 
      </div>   
    </nav>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>      
   <%= yield %>
 </body>
</html>

app/views/posts/_form.html.erb
<%= form_for :post, url: posts_path do |f| %>
  <p>
	<%= f.label :title %>
	<%= f.text_field :title %>
  </p>  


  <p>
	<%= f.label :body %>
	<%= f.text_area :body %>
  </p>


  <p>
	<%= f.submit %>
  </p>
 <% end %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= render 'form' %>

app/views/posts/index.html.erb
 <% @posts.each do |post| %>
   <h2><%= post.title %></h2>
   <div><%= post.body %></div>
   <div><%= post.user.email %></div>
   <br>
   <%= link_to "Read Post", post %>
 <% end %>  

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= form_for :post, url: posts_path do |f| %>
  <p>
	<%= f.label :title %>
	<%= f.text_field :title %>
  </p>  


  <p>
	<%= f.label :body %>
	<%= f.text_area :body %>
  </p>


  <p>
	<%= f.submit %>
  </p>
 <% end %>

app/views/posts/show.html.erb
<h1 class="title">
   <%= @post.title %>
 </h1>
 
 <p class="date">
 	Submitted <%= time_ago_in_words(@post.created_at) %> ago
 </p>	


  <p class="body">
  	<%= @post.body %>
  </p>

  <%= link_to "Back", root_path, class: "btn btn-default" %>
  <%= link_to "Edit", edit_post_path, class: "btn btn-default" %>	
  <%= link_to "Delete", post_path, method: :delete, data: { confirm: "Are you sure?"}, class: "btn btn-default" %>